services:
  website:
    build:
      context: .
      target: development
    restart: unless-stopped
    command: pnpm dev:website --host=0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  admin:
    build:
      context: .
      target: development
    restart: unless-stopped
    command: pnpm dev:admin --host=0.0.0
    ports:
      - '4000:4000'
    volumes:
      - .:/app
      - /app/node_modules
